[env]
SYNCTHING_VERSION = "{{ get_env(name='SYNCTHING_VERSION', default='1.30.0') }}"
SYNCTHING_GUI_USER = "{{ get_env(name='SYNCTHING_GUI_USER', default='admin') }}"
SYNCTHING_GUI_PASSWORD = "{{ get_env(name='SYNCTHING_GUI_PASSWORD', default='admin') }}"
SYNCTHING_HOME_DIR = "{{ get_env(name='SYNCTHING_HOME_DIR', default='/storage') }}"
